#!/bin/bash
# ============================================================
# Roadmap OS — Autonomous Fix Runner v7
# ============================================================
# Covers: Date picker context, edit row nav fix, add initiative
#         shortcut, Add Row→Add Product rename, settings reorg,
#         desktop↔web data sync investigation + fix.
#
# Usage:
#   1. cd into your pm-roadmapper repo root
#   2. Copy ROADMAP_OS_FIXES_V7.md into the repo root
#   3. Ensure CLAUDE.md is in the repo root
#   4. Run: bash run-fixes-v7.sh
# ============================================================

if [ ! -f "renderer/index.html" ]; then
  echo "❌ Run this from the pm-roadmapper repo root (where renderer/index.html lives)"
  exit 1
fi

echo "# Roadmap OS Fix Log v7 — $(date '+%Y-%m-%d %H:%M')" > FIX_LOG_V7.md
echo "" >> FIX_LOG_V7.md
echo "Auto-generated by the autonomous fix runner v7." >> FIX_LOG_V7.md
echo "" >> FIX_LOG_V7.md

claude --dangerously-skip-permissions "You are working on the Roadmap OS codebase. This is an Electron + Vercel web app with a single-file renderer/index.html SPA, plus main.js (Electron main process) and web/shim/electronAPI.js (web shim).

Your job: execute EVERY fix in ROADMAP_OS_FIXES_V7.md sequentially and autonomously. 6 fixes total. Do NOT ask questions. Do NOT stop between fixes.

START by reading ROADMAP_OS_FIXES_V7.md in full. Also read CLAUDE.md for project context. Then investigate the codebase — you'll need to read main.js and web/shim/electronAPI.js in addition to renderer/index.html for the sync fix. Log initial findings in FIX_LOG_V7.md.

Then execute Fix 1 through Fix 6 in order. For each:
1. Investigate (grep, read code in renderer/index.html, main.js, AND web/shim/electronAPI.js)
2. Implement
3. Self-review
4. Log in FIX_LOG_V7.md
5. Move to next fix immediately

CRITICAL PRIORITY — Fix 6 (Data Sync):
This is the MOST IMPORTANT fix. The desktop and web apps show different data for the same user. You MUST:
- Read main.js to understand how Electron saves/loads data
- Read web/shim/electronAPI.js to understand how the web app saves/loads data
- Read supabase/functions/sync-roadmap/index.ts to understand the server sync
- Map the complete data flow for BOTH platforms
- Identify WHY they diverge (local-only saves? different user IDs? load order?)
- Fix it so Supabase is the source of truth and both platforms sync correctly
- Fix profile picture storage to use Supabase Storage (not local)
This fix touches THREE files (renderer, main.js, shim) — be thorough.

OTHER FIXES are UI-level and stay in renderer/index.html only:
- Fix 1: Date picker defaults to current quarter
- Fix 2: Edit row links don't break navigation
- Fix 3: Add Initiative shortcut on three-dot menu
- Fix 4: Rename Add Row → Add Product
- Fix 5: Settings moves to profile menu, Style/Brand/TPL moves to Artefacts

After all fixes: bump version, rebuild web (cd web && npm run build), commit, write summary in FIX_LOG_V7.md.

Begin now. Read ROADMAP_OS_FIXES_V7.md first."
