#!/bin/bash
# ============================================================
# Roadmap OS — Autonomous Fix Runner v9
# ============================================================
# Covers: CIQ template UX (icons, focused view, save fix,
#         search), team management overhaul, Strategy→Reports
#         Dashboard rename + change log + multi-period capacity,
#         My Capacity move to CIQ, today line fix (3rd attempt),
#         date range filter, notifications/alerts system,
#         dashboard cards, CIQ page cleanup.
#
# Usage:
#   1. cd into your pm-roadmapper repo root
#   2. Copy ROADMAP_OS_FIXES_V9.md into the repo root
#   3. Ensure CLAUDE.md is in the repo root
#   4. Run: bash run-fixes-v9.sh
# ============================================================

if [ ! -f "renderer/index.html" ]; then
  echo "❌ Run this from the pm-roadmapper repo root (where renderer/index.html lives)"
  exit 1
fi

echo "# Roadmap OS Fix Log v9 — $(date '+%Y-%m-%d %H:%M')" > FIX_LOG_V9.md
echo "" >> FIX_LOG_V9.md
echo "Auto-generated by the autonomous fix runner v9." >> FIX_LOG_V9.md
echo "" >> FIX_LOG_V9.md

claude --dangerously-skip-permissions "You are working on the Roadmap OS codebase. This is an Electron + Vercel web app with a single-file renderer/index.html SPA containing all UI, logic, and styles.

Your job: execute EVERY fix in ROADMAP_OS_FIXES_V9.md sequentially and autonomously. 11 fixes total. Do NOT ask questions. Do NOT stop between fixes.

START by reading ROADMAP_OS_FIXES_V9.md in full. Also read CLAUDE.md for project context. Then investigate the codebase. Log initial findings in FIX_LOG_V9.md.

Then execute Fix 1 through Fix 11 in order. For each:
1. Investigate (grep, read code sections)
2. Implement
3. Self-review (re-read, check syntax, verify BOTH light and dark mode)
4. Log in FIX_LOG_V9.md
5. Move to next fix immediately

CRITICAL PRIORITIES — READ CAREFULLY:
1. Fix 7 (today line) — This has been reported THREE TIMES across v2, v8, and now v9. Read the ENTIRE today line function, understand every line, find the EXACT bug. Common issues: wrong container element, getTimelineStartDate returning null, percentage calculation using wrong units, or function called before DOM paint. Use requestAnimationFrame(requestAnimationFrame(positionTodayLine)) for timing. Test with the FY month configuration. DO NOT just rewrite the function without understanding why the old one fails.

2. Fix 3 (edit team) — The modal STACKS (opens multiple copies). Call closeAllModals() FIRST. The form must have NO horizontal scrollbar (overflow-x:hidden, max-width:480px, all inputs width:100%). Include member dropdown from org users, invite by email, team description, and role assignment.

3. Fix 5 (change log) — This hooks into EVERY roadmap modification function. grep -n 'function addRow\|function editRow\|function deleteRow\|function addSection\|function editSection\|function deleteSection\|function addInitiative\|function saveRow' renderer/index.html to find them ALL. Add logRoadmapChange() calls to each one.

4. Fix 9 (notifications) — Check if supabase/functions/notifications-api/ exists. If yes, use it for email notifications. If not, implement frontend and log the backend requirement.

DESIGN RULES:
- Template icons are SVG (stroke-based, currentColor, 24x24 viewBox)
- Health indicators: <svg><circle r='5' fill='#22c55e'/></svg> for green, #eab308 for yellow, #ef4444 for red — NOT emoji
- All dark mode via CSS variables
- No horizontal scrollers on any modal/popup — use overflow-x:hidden and max-width
- Capacity views must support daily/weekly/monthly/quarterly/yearly period switching

After all fixes: bump version, rebuild web (cd web && npm run build), commit, write summary in FIX_LOG_V9.md.

Begin now. Read ROADMAP_OS_FIXES_V9.md first."
