#!/bin/bash
# ============================================================
# Roadmap OS — Autonomous Fix Runner v12
# ============================================================
# Covers: Select All (G2M, Task Library, Planning), hours
#         tooltip, timeline pill sync + filters + scroller,
#         edit team members dropdown, email invite fix (Resend),
#         team logo + card display, CIQ template count fix,
#         team capacity on dashboard, portfolio overview removal.
#
# Usage:
#   1. cd into your pm-roadmapper repo root
#   2. Copy ROADMAP_OS_FIXES_V12.md into the repo root
#   3. Ensure CLAUDE.md is in the repo root
#   4. Run: bash run-fixes-v12.sh
# ============================================================

if [ ! -f "renderer/index.html" ]; then
  echo "❌ Run this from the pm-roadmapper repo root (where renderer/index.html lives)"
  exit 1
fi

echo "# Roadmap OS Fix Log v12 — $(date '+%Y-%m-%d %H:%M')" > FIX_LOG_V12.md
echo "" >> FIX_LOG_V12.md
echo "Auto-generated by the autonomous fix runner v12." >> FIX_LOG_V12.md
echo "" >> FIX_LOG_V12.md

claude --dangerously-skip-permissions "You are working on the Roadmap OS codebase. Electron + Vercel web app, single-file renderer/index.html SPA.

Your job: execute EVERY fix in ROADMAP_OS_FIXES_V12.md sequentially and autonomously. 9 fixes total. Do NOT ask questions. Do NOT stop between fixes.

START by reading ROADMAP_OS_FIXES_V12.md in full. Also read CLAUDE.md. Investigate codebase. Log findings in FIX_LOG_V12.md.

CRITICAL PRIORITIES:
1. Fix 5 (Email invite Resend error) — Read supabase/functions/send-invite/index.ts. The error is 'check Resend config' which means either RESEND_API_KEY isn't set, the from domain isn't verified, or the function swallows the real error. Fix the edge function to return the specific error. Update the email HTML template to be branded.
2. Fix 3 (Timeline) — Three sub-fixes: pill width sync after date edit, working filters, horizontal scroller. Read the entire timeline rendering function before changing anything.
3. Fix 7 (CIQ templates only 2) — Count how many templates getDefaultTemplates() actually returns. If it's 2, all the templates from v3 were never added. Add them all now.
4. Fix 1 (Select All) — Reusable pattern: toggleAllCheckboxes(containerId, checked) with indeterminate state on the select-all checkbox. Apply to G2M tab, Task Library tab, and Planning page.

EDGE FUNCTION NOTE: Fix 5 requires editing supabase/functions/send-invite/index.ts (Deno, not Node.js). Read the existing code first, then fix the error handling and update the email HTML template.

After all fixes: bump version, rebuild web (cd web && npm run build), commit, write summary.

Begin now. Read ROADMAP_OS_FIXES_V12.md first."
