#!/bin/bash
# ============================================================
# Roadmap OS — Autonomous Fix Runner v5
# ============================================================
# Covers: Template categorization (generic vs org), toolbar
#         centering global fix, template editor/builder,
#         checklist browse templates, competitive analysis
#         research areas, nav state fix, feedback system,
#         Capacity IQ template picker.
#
# Usage:
#   1. cd into your pm-roadmapper repo root
#   2. Copy ROADMAP_OS_FIXES_V5.md into the repo root
#   3. Ensure CLAUDE.md is in the repo root
#   4. Run: bash run-fixes-v5.sh
# ============================================================

if [ ! -f "renderer/index.html" ]; then
  echo "❌ Run this from the pm-roadmapper repo root (where renderer/index.html lives)"
  exit 1
fi

echo "# Roadmap OS Fix Log v5 — $(date '+%Y-%m-%d %H:%M')" > FIX_LOG_V5.md
echo "" >> FIX_LOG_V5.md
echo "Auto-generated by the autonomous fix runner v5." >> FIX_LOG_V5.md
echo "" >> FIX_LOG_V5.md

claude --dangerously-skip-permissions "You are working on the Roadmap OS codebase. This is an Electron + Vercel web app with a single-file renderer/index.html SPA containing all UI, logic, and styles.

Your job: execute EVERY fix in ROADMAP_OS_FIXES_V5.md sequentially and autonomously. 10 fixes total. Do NOT ask questions. Do NOT stop between fixes.

START by reading ROADMAP_OS_FIXES_V5.md in full. Also read CLAUDE.md for project context and design rules. Then investigate the codebase. Log initial findings in FIX_LOG_V5.md.

Then execute Fix 1 through Fix 10 in order. For each:
1. Investigate (grep, read code sections)
2. Implement
3. Self-review (re-read, check syntax, verify BOTH light and dark mode)
4. Log in FIX_LOG_V5.md
5. Move to next fix immediately

CRITICAL PRIORITIES:
1. Fix 2 (toolbar centering) — GLOBAL CSS fix, not page-by-page. This has been reported in v3, v4, and v5. Make it permanent with a reusable .page-toolbar class applied everywhere.
2. Fix 3 (template editor) — The template system is the backbone. Platform templates must be editable: add tasks, pull from task library, save as org template, import to plan.
3. Fix 7 (navigation state) — Two bugs: wrong tab highlighted + browser back broken. Both are core UX.
4. Fix 9 (feedback system) — Full build-out with public submission, inbox, voting, initiative linking.

KEY ARCHITECTURAL DECISIONS:
- getAllTemplates() is the SINGLE source of truth for templates everywhere. It returns platform + organisation templates combined.
- Templates have type: 'platform' (built-in) or 'organisation' (user-created/customised).
- Task Library (currentData.taskLibrary) is accessible from template creation, template editing, and any task picker.
- Research areas on competitive analysis are PER-USER (stored in JSONB blob), not global/hardcoded.
- The toolbar centering fix is a CSS class (.page-toolbar) applied globally — not inline styles on each page.

After all fixes: bump version, rebuild web (cd web && npm run build), commit, write summary in FIX_LOG_V5.md.

Begin now. Read ROADMAP_OS_FIXES_V5.md first."
