#!/bin/bash
# ============================================================
# Roadmap OS — Autonomous Fix Runner v2
# ============================================================
# Covers: Dark mode overhaul, emoji→SVG replacement,
#         task library, document repository, initiative linking,
#         UI alignment, and more.
#
# Usage:
#   1. cd into your pm-roadmapper repo root
#   2. Copy ROADMAP_OS_FIXES_V2.md into the repo root
#   3. Run: bash run-fixes-v2.sh
# ============================================================

# Ensure we're in the repo
if [ ! -f "renderer/index.html" ]; then
  echo "❌ Run this from the pm-roadmapper repo root (where renderer/index.html lives)"
  exit 1
fi

# Create the fix log
echo "# Roadmap OS Fix Log v2 — $(date '+%Y-%m-%d %H:%M')" > FIX_LOG_V2.md
echo "" >> FIX_LOG_V2.md
echo "Auto-generated by the autonomous fix runner v2." >> FIX_LOG_V2.md
echo "" >> FIX_LOG_V2.md

# Launch Claude Code
claude --dangerously-skip-permissions "You are working on the Roadmap OS codebase (formerly PM Roadmapper). This is an Electron + Vercel web app with a single 23k-line renderer/index.html SPA, all UI/logic/styles in that one file.

Your job: execute EVERY fix in ROADMAP_OS_FIXES_V2.md sequentially and autonomously. Do NOT ask questions. Do NOT stop between fixes.

START by reading ROADMAP_OS_FIXES_V2.md in full. Then investigate the codebase structure (dark mode mechanism, emoji locations, routing pattern, page structure). Log initial findings in FIX_LOG_V2.md.

Then execute Fix 1 through Fix 16 in order. For each:
1. Investigate (grep, read code)
2. Implement
3. Self-review (re-read changes, check syntax, verify dark mode)
4. Log in FIX_LOG_V2.md
5. Move to next fix immediately

PRIORITY ORDER for maximum impact:
- Fix 1 (global dark mode) and Fix 3 (global emoji replacement) are foundational — do these FIRST as they affect everything else.
- Then do the feature fixes (4, 5, 6, 7, 8, 9, 14B).
- Then do the targeted UI/UX fixes (2, 10, 11, 12, 13, 14A, 15, 16).

CRITICAL: The single biggest theme here is DARK MODE. White backgrounds with grey text is the #1 usability complaint. Be aggressive — find and fix EVERY instance. When in doubt, make it dark.

SECOND BIGGEST: EMOJI. Replace every Unicode emoji with clean SVG icons matching the sidebar nav style. Zero emoji should remain.

After all fixes: bump version, rebuild web (cd web && npm run build), commit with descriptive message, write summary in FIX_LOG_V2.md.

Begin now. Read ROADMAP_OS_FIXES_V2.md first."
