#!/bin/bash
# ============================================================
# Roadmap OS — Autonomous Fix Runner v10: Integrations
# ============================================================
# Builds the integration framework for Jira, GitHub, Slack,
# Asana, and Linear with two-way sync, OAuth flows,
# Supabase edge functions, webhook handlers, and an
# Integrations page UI.
#
# Usage:
#   1. cd into your pm-roadmapper repo root
#   2. Copy ROADMAP_OS_FIXES_V10.md into the repo root
#   3. Ensure CLAUDE.md is in the repo root
#   4. Run: bash run-fixes-v10.sh
# ============================================================

if [ ! -f "renderer/index.html" ]; then
  echo "❌ Run this from the pm-roadmapper repo root (where renderer/index.html lives)"
  exit 1
fi

echo "# Roadmap OS Fix Log v10: Integrations — $(date '+%Y-%m-%d %H:%M')" > FIX_LOG_V10.md
echo "" >> FIX_LOG_V10.md
echo "Auto-generated by the autonomous fix runner v10." >> FIX_LOG_V10.md
echo "" >> FIX_LOG_V10.md

claude --dangerously-skip-permissions "You are working on the Roadmap OS codebase. This is an Electron + Vercel web app. Your job: build the integration framework for 5 external tools.

IMPORTANT CONTEXT:
- Main renderer: renderer/index.html (single-file SPA)
- Edge functions: supabase/functions/ (Deno runtime, NOT Node.js)
- Existing auth pattern: supabase/functions/_shared/auth.ts
- Supabase project: nigusoyssktoebzscbwe (eu-west-1)
- App URL: https://app.pmroadmapper.com

Read ROADMAP_OS_FIXES_V10.md in full. Also read CLAUDE.md. Then read:
1. supabase/functions/_shared/auth.ts (understand the auth/CORS pattern)
2. supabase/config.toml (understand function config)
3. At least one existing edge function to understand the pattern

Then execute Fix 1 through Fix 8 in order:
1. Fix 1: Database migration (SQL file with 3 tables + RLS)
2. Fix 2: OAuth edge function (handles authorize + callback for all 5 providers)
3. Fix 3: Sync edge function (import + export for Jira, GitHub, Asana, Linear)
4. Fix 4: Webhook edge function (receives events from external tools)
5. Fix 5: Integration API edge function (project listing, config, manual sync)
6. Fix 6: Integrations page UI (cards, connect flow, configure modal)
7. Fix 7: Frontend sync functions (trigger, status, polling)
8. Fix 8: Setup guide (INTEGRATION_SETUP_GUIDE.md)

CRITICAL RULES:
- Edge functions are DENO, not Node.js. Use Deno imports (https://deno.land/, https://esm.sh/).
- DO NOT use require(). DO NOT use npm packages directly.
- OAuth tokens are SENSITIVE. Store in DB, never log, never return to frontend.
- Webhook endpoints MUST verify signatures before processing.
- SQL uses CREATE TABLE IF NOT EXISTS and follows existing migration patterns.
- config.toml: OAuth and webhook functions need verify_jwt = false (external callers). API function needs verify_jwt = true.
- ALL UI uses CSS variables for dark mode. Zero emoji. SVG icons for provider logos.
- The callback URL pattern is: https://nigusoyssktoebzscbwe.supabase.co/functions/v1/integrations-oauth/callback/{provider}

After all fixes: bump version, rebuild web, commit, write summary in FIX_LOG_V10.md.

Begin now. Read ROADMAP_OS_FIXES_V10.md first."
