#!/bin/bash
# ============================================================
# Roadmap OS — Autonomous Fix Runner v4
# ============================================================
# Covers: JSON import fix, template builder, document upload,
#         sign-up invites, browser back nav, Plans import,
#         toolbar alignment, template unification.
#
# Usage:
#   1. cd into your pm-roadmapper repo root
#   2. Copy ROADMAP_OS_FIXES_V4.md into the repo root
#   3. Ensure CLAUDE.md is in the repo root
#   4. Run: bash run-fixes-v4.sh
# ============================================================

if [ ! -f "renderer/index.html" ]; then
  echo "❌ Run this from the pm-roadmapper repo root (where renderer/index.html lives)"
  exit 1
fi

echo "# Roadmap OS Fix Log v4 — $(date '+%Y-%m-%d %H:%M')" > FIX_LOG_V4.md
echo "" >> FIX_LOG_V4.md
echo "Auto-generated by the autonomous fix runner v4." >> FIX_LOG_V4.md
echo "" >> FIX_LOG_V4.md

claude --dangerously-skip-permissions "You are working on the Roadmap OS codebase. This is an Electron + Vercel web app with a single-file renderer/index.html SPA containing all UI, logic, and styles.

Your job: execute EVERY fix in ROADMAP_OS_FIXES_V4.md sequentially and autonomously. 8 fixes total. Do NOT ask questions. Do NOT stop between fixes.

START by reading ROADMAP_OS_FIXES_V4.md in full. Also read CLAUDE.md for project context and design rules. Then investigate the codebase. Log initial findings in FIX_LOG_V4.md.

Then execute Fix 1 through Fix 8 in order. For each:
1. Investigate (grep, read code sections)
2. Implement
3. Self-review (re-read, check syntax, verify BOTH light and dark mode)
4. Log in FIX_LOG_V4.md
5. Move to next fix immediately

CRITICAL PRIORITIES:
1. Fix 1 (JSON import broken) — users cannot load their data on web
2. Fix 3 (Template Builder) — centerpiece feature, powers Plans/Todo/Checklist/CapacityIQ
3. Fix 8 (Browser back nav) — fundamental web UX, currently broken

KEY CONTEXT:
- The web app uses a shim (web/shim/electronAPI.js) that re-implements Electron IPC methods with browser APIs. File operations often break here — check the shim carefully for Fix 1.
- The showPage() function controls all SPA navigation. Fix 8 hooks into this with history.pushState.
- Fix 3 creates a reusable Template Builder modal that ALL modules can call. Build it as a self-contained component.
- Fix 4 (document upload) needs Supabase Storage for actual file storage. Check if the 'attachments' bucket is configured.
- Fix 5 (Google integration) will likely need backend OAuth scope changes — implement the UI and stubs, document what's needed.

After all fixes: bump version, rebuild web (cd web && npm run build), commit, write summary in FIX_LOG_V4.md.

Begin now. Read ROADMAP_OS_FIXES_V4.md first."
