#!/bin/bash
# ============================================================
# Roadmap OS — Autonomous Fix Runner v3
# ============================================================
# Covers: JSON upload, profile photo, task library, team mgmt,
#         stacked roadmaps, templates, onboarding flow,
#         contrast overhaul, checklist rename, and more.
#
# Usage:
#   1. cd into your pm-roadmapper repo root
#   2. Copy ROADMAP_OS_FIXES_V3.md into the repo root
#   3. Ensure CLAUDE.md is in the repo root (from v2)
#   4. Run: bash run-fixes-v3.sh
# ============================================================

if [ ! -f "renderer/index.html" ]; then
  echo "❌ Run this from the pm-roadmapper repo root (where renderer/index.html lives)"
  exit 1
fi

echo "# Roadmap OS Fix Log v3 — $(date '+%Y-%m-%d %H:%M')" > FIX_LOG_V3.md
echo "" >> FIX_LOG_V3.md
echo "Auto-generated by the autonomous fix runner v3." >> FIX_LOG_V3.md
echo "" >> FIX_LOG_V3.md

claude --dangerously-skip-permissions "You are working on the Roadmap OS codebase. This is an Electron + Vercel web app with a single-file renderer/index.html SPA containing all UI, logic, and styles.

Your job: execute EVERY fix in ROADMAP_OS_FIXES_V3.md sequentially and autonomously. 20 fixes total. Do NOT ask questions. Do NOT stop between fixes.

START by reading ROADMAP_OS_FIXES_V3.md in full. Also read CLAUDE.md for project context and design rules. Then investigate the codebase (grep for key patterns). Log initial findings in FIX_LOG_V3.md.

Then execute Fix 1 through Fix 20 in order. For each:
1. Investigate (grep, read code sections)
2. Implement
3. Self-review (re-read, check syntax, verify BOTH light mode AND dark mode)
4. Log in FIX_LOG_V3.md
5. Move to next fix immediately

CRITICAL PRIORITIES:
1. Fix 1 (JSON upload + loading animation) — users can't import data
2. Fix 3 (task library population) — seed 200+ realistic tasks
3. Fix 11 (template quality overhaul) — 10+ realistic templates
4. Fix 15 (onboarding flow) — critical for new user experience
5. Fix 19 (contrast audit) — do this LAST as a final sweep across everything

DESIGN RULES (from CLAUDE.md):
- ZERO emoji — SVG icons only
- Dark mode mandatory on every element
- Light mode must also have proper contrast (no light text on light bg)
- Match the roadmap page's design language everywhere
- Realistic content in templates — real PM terminology, real timeframes

After all fixes: bump version, rebuild web, commit, write summary in FIX_LOG_V3.md.

Begin now. Read ROADMAP_OS_FIXES_V3.md first."
