#!/bin/bash
# ============================================================
# Roadmap OS — Autonomous Fix Runner v8
# ============================================================
# Covers: Task library sync from templates, today line fix,
#         burger menu auto-close, page removals (UCR, sprints,
#         task ref, initiatives from CIQ), Capacity IQ dashboard
#         overhaul, monthly capacity reports, help widget,
#         feedback page branding, nav cleanup.
#
# Usage:
#   1. cd into your pm-roadmapper repo root
#   2. Copy ROADMAP_OS_FIXES_V8.md into the repo root
#   3. Ensure CLAUDE.md is in the repo root
#   4. Run: bash run-fixes-v8.sh
# ============================================================

if [ ! -f "renderer/index.html" ]; then
  echo "❌ Run this from the pm-roadmapper repo root (where renderer/index.html lives)"
  exit 1
fi

echo "# Roadmap OS Fix Log v8 — $(date '+%Y-%m-%d %H:%M')" > FIX_LOG_V8.md
echo "" >> FIX_LOG_V8.md
echo "Auto-generated by the autonomous fix runner v8." >> FIX_LOG_V8.md
echo "" >> FIX_LOG_V8.md

claude --dangerously-skip-permissions "You are working on the Roadmap OS codebase. This is an Electron + Vercel web app with a single-file renderer/index.html SPA containing all UI, logic, and styles.

Your job: execute EVERY fix in ROADMAP_OS_FIXES_V8.md sequentially and autonomously. 9 fixes total. Do NOT ask questions. Do NOT stop between fixes.

START by reading ROADMAP_OS_FIXES_V8.md in full. Also read CLAUDE.md for project context. Then investigate the codebase. Log initial findings in FIX_LOG_V8.md.

Then execute Fix 1 through Fix 9 in order. For each:
1. Investigate (grep, read code sections)
2. Implement
3. Self-review (re-read, check syntax, verify BOTH light and dark mode)
4. Log in FIX_LOG_V8.md
5. Move to next fix immediately

CRITICAL PRIORITIES:
1. Fix 1 (task library sync) — All template tasks MUST appear in the task library. Call syncTemplateTasksToLibrary() on startup. After fix, the task count should be well over 173.
2. Fix 4 (page removals) — Surgical: remove UI elements but preserve user data in JSONB blob. Watch for broken references after removal.
3. Fix 6 (Capacity IQ dashboard) — Real data aggregation from plans, teams, initiatives. Not placeholders. Period switching (daily/weekly/monthly/quarterly/yearly). Personal capacity config.
4. Fix 8 (help widget) — Floating FAB in bottom-right. Clean SVG icons. Route to email.

DESIGN RULES:
- Health indicators (green/yellow/red) use SVG circles: <circle cx='6' cy='6' r='5' fill='#22c55e'/> — NOT emoji
- All dark mode via CSS variables
- Zero emoji anywhere
- Tables and data views must be responsive and readable in both modes

After all fixes: bump version, rebuild web (cd web && npm run build), commit, write summary in FIX_LOG_V8.md.

Begin now. Read ROADMAP_OS_FIXES_V8.md first."
