#!/bin/bash
# ============================================================
# Roadmap OS — Autonomous Fix Runner v11
# ============================================================
# Covers: Onboarding team setup, loading spinners, dummy data,
#         initiative enhancements (revenue, labels, owner,
#         comments, archive, duplicate, watch), browser back
#         DEFINITIVE fix, plan sharing + follow.
#
# Usage:
#   1. cd into your pm-roadmapper repo root
#   2. Copy ROADMAP_OS_FIXES_V11.md into the repo root
#   3. Ensure CLAUDE.md is in the repo root
#   4. Run: bash run-fixes-v11.sh
# ============================================================

if [ ! -f "renderer/index.html" ]; then
  echo "❌ Run this from the pm-roadmapper repo root (where renderer/index.html lives)"
  exit 1
fi

echo "# Roadmap OS Fix Log v11 — $(date '+%Y-%m-%d %H:%M')" > FIX_LOG_V11.md
echo "" >> FIX_LOG_V11.md
echo "Auto-generated by the autonomous fix runner v11." >> FIX_LOG_V11.md
echo "" >> FIX_LOG_V11.md

claude --dangerously-skip-permissions "You are working on the Roadmap OS codebase. This is an Electron + Vercel web app with a single-file renderer/index.html SPA.

Your job: execute EVERY fix in ROADMAP_OS_FIXES_V11.md sequentially and autonomously. 9 fixes total. Do NOT ask questions. Do NOT stop between fixes.

START by reading ROADMAP_OS_FIXES_V11.md in full. Also read CLAUDE.md. Then investigate the codebase. Log initial findings in FIX_LOG_V11.md.

CRITICAL — READ THIS BEFORE STARTING:

Fix 8 (Browser Back) is the #1 priority and has been broken since v4 (reported 4 times). The fix document provides a complete NavManager singleton that REPLACES all existing navigation state management. You must:
1. Read the ENTIRE existing showPage function and ALL popstate/pushState code
2. Remove ALL competing navigation code (duplicate pushState calls, hash assignments, etc.)
3. Replace with the NavManager pattern from the fix document
4. Ensure EVERY showPage call in the entire file routes through NavManager.goTo()
5. After login: call NavManager.onLoginSuccess() which does replaceState to prevent back-to-login

Fix 6 (Edit Initiative) is the biggest UI fix — adds revenue field, multi-label selector, owner dropdown, timestamps, and a full threaded comments system with likes and replies. Build it section by section, test each part.

Fix 7 (Archive/Duplicate/Watch) creates new data structures (currentData.archive, row.watchers). Make sure these are included in any backup/export functionality.

Fix 4 (Sample Data) loads realistic dummy data for first-time users with a dismissible banner. The data should look like a real product roadmap, not placeholder text.

Fix 9 (Plan Sharing) needs deep linking — the share link must survive the signup/onboarding flow and redirect to the plan afterward using sessionStorage.

RECOMMENDED ORDER:
1. Fix 8 FIRST (browser back — foundational)
2. Fix 2 (loading spinner — used by other fixes)
3. Fix 3 (remove free trial text — quick search/replace)
4. Fix 5 (data model extension — needed before Fix 6)
5. Fix 6 (edit initiative UI — builds on Fix 5)
6. Fix 7 (archive/duplicate/watch — builds on Fix 5/6)
7. Fix 1 (onboarding team step)
8. Fix 4 (sample data)
9. Fix 9 (plan sharing + follow)

After all fixes: bump version, rebuild web (cd web && npm run build), commit, write summary in FIX_LOG_V11.md.

Begin now. Read ROADMAP_OS_FIXES_V11.md first."
