#!/bin/bash
# ============================================================
# Roadmap OS — Autonomous Fix Runner v6
# ============================================================
# Covers: Quarter/FY management, template builder Select All,
#         Add Task tab cleanup, sidebar reorganization,
#         To-Do edit + auto-pull + timesheet/capacity tabs,
#         dark mode DEFINITIVE audit, colours button removal.
#
# Usage:
#   1. cd into your pm-roadmapper repo root
#   2. Copy ROADMAP_OS_FIXES_V6.md into the repo root
#   3. Ensure CLAUDE.md is in the repo root
#   4. Run: bash run-fixes-v6.sh
# ============================================================

if [ ! -f "renderer/index.html" ]; then
  echo "❌ Run this from the pm-roadmapper repo root (where renderer/index.html lives)"
  exit 1
fi

echo "# Roadmap OS Fix Log v6 — $(date '+%Y-%m-%d %H:%M')" > FIX_LOG_V6.md
echo "" >> FIX_LOG_V6.md
echo "Auto-generated by the autonomous fix runner v6." >> FIX_LOG_V6.md
echo "" >> FIX_LOG_V6.md

claude --dangerously-skip-permissions "You are working on the Roadmap OS codebase. This is an Electron + Vercel web app with a single-file renderer/index.html SPA containing all UI, logic, and styles.

Your job: execute EVERY fix in ROADMAP_OS_FIXES_V6.md sequentially and autonomously. 9 fixes total. Do NOT ask questions. Do NOT stop between fixes.

START by reading ROADMAP_OS_FIXES_V6.md in full. Also read CLAUDE.md for project context and design rules. Then investigate the codebase. Log initial findings in FIX_LOG_V6.md.

Then execute Fix 1 through Fix 9 in order. For each:
1. Investigate (grep, read code sections)
2. Implement
3. Self-review (re-read, check syntax, verify BOTH light and dark mode)
4. Log in FIX_LOG_V6.md
5. Move to next fix immediately

CRITICAL PRIORITIES:
1. Fix 7 (dark mode DEFINITIVE audit) — This is INFRASTRUCTURE, not a patch. Create a bulletproof CSS variable system, then find and replace EVERY hardcoded color in the entire file. This must be the LAST TIME dark mode is ever an issue.
2. Fix 3 (template builder Select All) — Fundamental UX: Select All per template, per category, global. Accumulated selection across templates.
3. Fix 8 (sidebar reorg) — Major nav restructure: Roadmap actions and Data actions move into legend dropdowns.
4. Fix 6 (To-Do overhaul) — Three sub-fixes: add task parity, edit task, auto-pull from Plans.

KEY CONTEXT:
- The dark mode fix (Fix 7) should be done BEFORE other fixes so all new UI elements automatically inherit the correct colors.
- The template builder enhancements (Fix 3) build on the existing builder from v4/v5. Check what state it's in first.
- The sidebar reorg (Fix 8) moves items from one location to another — ensure functions still work after the move.
- The To-Do auto-pull (Fix 6C) creates bidirectional sync between Plans and To-Do — be careful with infinite loops.

RECOMMENDED ORDER (override sequential if this is more efficient):
1. Fix 7 first (dark mode infrastructure)
2. Then Fix 2 (template import broken — quick diagnosis)
3. Then Fix 3 (template builder Select All)
4. Then Fix 4 (Add Task tab cleanup)
5. Then Fix 5 (remove Colours + category)
6. Then Fix 6 (To-Do overhaul)
7. Then Fix 1 (quarter/FY management)
8. Then Fix 8 (sidebar reorg)
9. Then Fix 9 (timesheet/capacity tabs)

After all fixes: bump version, rebuild web (cd web && npm run build), commit, write summary in FIX_LOG_V6.md.

Begin now. Read ROADMAP_OS_FIXES_V6.md first."
