#!/bin/bash
# ============================================================
# Roadmap OS — Autonomous Fix Runner
# ============================================================
# Usage:
#   1. cd into your pm-roadmapper repo root
#   2. Copy ROADMAP_OS_FIXES.md into the repo root
#   3. Run: bash run-fixes.sh
#
# This launches Claude Code with a structured prompt that
# works through all 16 fixes sequentially without intervention.
# ============================================================

# Ensure we're in the repo
if [ ! -f "renderer/index.html" ]; then
  echo "❌ Run this from the pm-roadmapper repo root (where renderer/index.html lives)"
  exit 1
fi

# Create the fix log
echo "# Roadmap OS Fix Log — $(date '+%Y-%m-%d %H:%M')" > FIX_LOG.md
echo "" >> FIX_LOG.md
echo "Auto-generated by the autonomous fix runner." >> FIX_LOG.md
echo "" >> FIX_LOG.md

# Launch Claude Code with the full autonomous prompt
claude --dangerously-skip-permissions "You are working on the Roadmap OS codebase (formerly PM Roadmapper). This is an Electron + Vercel web app with a single 23k-line renderer/index.html SPA. Your job is to work through EVERY fix listed in ROADMAP_OS_FIXES.md sequentially, autonomously, without asking questions. 

START by reading ROADMAP_OS_FIXES.md in full. Then read the first 200 lines of renderer/index.html to understand the structure. Then grep for key patterns (routing function, edit handlers, dark mode mechanism, nav structure). Log your initial findings in FIX_LOG.md.

Then execute Fix 1 through Fix 16 in order. For each fix:
1. Investigate the issue (grep, read relevant code sections)
2. Implement the fix
3. Self-review your changes (re-read them, check syntax)
4. Log what you did in FIX_LOG.md
5. Move to the next fix immediately

CRITICAL RULES:
- Do NOT ask me any questions. Make your best judgment and document decisions in FIX_LOG.md.
- Do NOT stop between fixes. Keep going until all 16 are done.
- Do NOT break existing functionality. Be surgical with edits.
- After all fixes: bump version to 1.28.0 in package.json, rebuild web (cd web && npm run build), and write a final summary in FIX_LOG.md.

Begin now. Read ROADMAP_OS_FIXES.md first."
